export enum FormatDateConst {

  /**
   * 时间格式 yyyy-MM-dd HH:mm:ss
   */
  yyyy_MM_dd_HHmmss = "yyyy-MM-dd HH:mm:ss",

  /**
   * 时间格式 yyyy-MM-dd HH:mm
   */
  yyyy_MM_dd_HHmm = "yyyy-MM-dd HH:mm",

  /**
   * 时间格式 yyyyMMddHHmmssSSS
   */
  yyyyMMddHHmmssSSS = "yyyyMMddHHmmssSSS",

  /**
   * 时间格式 yyyy年 MM月dd日HH时
   */
  yyyyMMddHHmm = "yyyy年 MM月dd日HH时",

  /**
   * 时间格式 yyyy-MM-dd
   */
  yyyy_MM_dd = "yyyy-MM-dd",

  /**
   * 时间格式 HH:mm
   */
  HHmm = "HH:mm",

  /**
   * 时间格式 HH:mm:ss
   */
  HHmmss = "HH:mm:ss",

  /**
   * 时间格式 MM-dd HH:mm
   */
  MM_dd_HHmm = "MM-dd HH:mm",

  /**
   * 时间格式 yyyy
   */
  yyyy = "yyyy"

}