export class RouterConst {
  private constructor() {
  }

  static readonly PATH_ADD_TASK = "pages/example/AddTaskPage"
  static readonly PATH_HOME_PAGE = "pages/HomePage"
  static readonly PATH_STORAGE = "pages/example/Page09_Storage"
  static readonly PATH_ArrayStatePage = "pages/entry/state/ArrayStatePage"
  static readonly PATH_ArrayStateWithPresenterPage = "pages/entry/state/ArrayStateWithPresenterPage"
}